"""Seed property listings for Dubai and Abu Dhabi."""

PROPERTIES = [
    {
        "id": "dt-burj-view-3br",
        "title": "Burj Khalifa View Residence",
        "area": "Downtown Dubai",
        "type": "apartment",
        "bedrooms": 3,
        "bathrooms": 3,
        "sizeSqft": 2100,
        "priceAED": 4200000,
        "rentAED": 220000,
        "style": "modern",
        "description": "Corner unit with floor-to-ceiling Burj views, open kitchen, and a family-sized living area.",
        "amenities": ["burj view", "gym", "pool", "concierge", "parking"],
        "pricePerSqft": 2000,
        "lat": 25.1972,
        "lng": 55.2744,
        "cameraHeading": 45,
        "images": [
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Sarah Al Maktoum",
            "agency": "Downtown Living",
            "phone": "+971 50 123 4567",
            "whatsapp": "971501234567",
        },
    },
    {
        "id": "dt-opera-2br",
        "title": "Opera District Sky Apartment",
        "area": "Downtown Dubai",
        "type": "apartment",
        "bedrooms": 2,
        "bathrooms": 2,
        "sizeSqft": 1450,
        "priceAED": 2850000,
        "rentAED": 165000,
        "style": "minimalist",
        "description": "Bright minimalist apartment steps from Dubai Opera and the Dubai Mall boulevard.",
        "amenities": ["gym", "pool", "balcony", "parking"],
        "pricePerSqft": 1965,
        "lat": 25.1955,
        "lng": 55.2718,
        "cameraHeading": 120,
        "images": [
            "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Omar Hassan",
            "agency": "Opera Estates",
            "phone": "+971 55 234 5678",
            "whatsapp": "971552345678",
        },
    },
    {
        "id": "dt-boulevard-penthouse",
        "title": "Boulevard Penthouse Suite",
        "area": "Downtown Dubai",
        "type": "penthouse",
        "bedrooms": 4,
        "bathrooms": 5,
        "sizeSqft": 4200,
        "priceAED": 12500000,
        "rentAED": 650000,
        "style": "luxury",
        "description": "Duplex penthouse with private terrace, maid's room, and panoramic Downtown skyline views.",
        "amenities": ["burj view", "terrace", "gym", "pool", "concierge", "maid room"],
        "pricePerSqft": 2976,
        "lat": 25.1988,
        "lng": 55.2761,
        "cameraHeading": 200,
        "images": [
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Layla Rahman",
            "agency": "Elite Downtown",
            "phone": "+971 50 987 6543",
            "whatsapp": "971509876543",
        },
    },
    {
        "id": "dt-fountain-1br",
        "title": "Fountain Views Studio Plus",
        "area": "Downtown Dubai",
        "type": "apartment",
        "bedrooms": 1,
        "bathrooms": 1,
        "sizeSqft": 780,
        "priceAED": 1450000,
        "rentAED": 95000,
        "style": "modern",
        "description": "Compact but premium one-bed with direct Dubai Fountain views — ideal for professionals.",
        "amenities": ["fountain view", "gym", "pool", "parking"],
        "pricePerSqft": 1859,
        "lat": 25.1963,
        "lng": 55.2755,
        "images": [
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "James Okonkwo",
            "agency": "Fountain Homes",
            "phone": "+971 52 111 2233",
            "whatsapp": "971521112233",
        },
    },
    {
        "id": "dt-family-4br",
        "title": "Boulevard Family Residence",
        "area": "Downtown Dubai",
        "type": "apartment",
        "bedrooms": 4,
        "bathrooms": 4,
        "sizeSqft": 2800,
        "priceAED": 5800000,
        "rentAED": 310000,
        "style": "classic",
        "description": "Spacious family layout with separate dining, study nook, and two parking bays near schools.",
        "amenities": ["gym", "pool", "play area", "parking", "study"],
        "pricePerSqft": 2071,
        "lat": 25.1995,
        "lng": 55.2725,
        "cameraHeading": 310,
        "images": [
            "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Fatima Al Noor",
            "agency": "Family First Realty",
            "phone": "+971 56 444 5566",
            "whatsapp": "971564445566",
        },
    },
    {
        "id": "dt-industrial-loft",
        "title": "DIFC Edge Loft",
        "area": "Downtown Dubai",
        "type": "apartment",
        "bedrooms": 2,
        "bathrooms": 2,
        "sizeSqft": 1600,
        "priceAED": 3200000,
        "rentAED": 185000,
        "style": "industrial",
        "description": "Double-height loft with exposed concrete, black steel finishes, and walkable DIFC access.",
        "amenities": ["gym", "concierge", "parking", "high ceilings"],
        "pricePerSqft": 2000,
        "lat": 25.2048,
        "lng": 55.2708,
        "images": [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Marcus Chen",
            "agency": "Urban Loft Co",
            "phone": "+971 50 777 8899",
            "whatsapp": "971507778899",
        },
    },
    {
        "id": "jm-beach-villa-5br",
        "title": "Jumeirah Beach Road Villa",
        "area": "Jumeirah",
        "type": "villa",
        "bedrooms": 5,
        "bathrooms": 6,
        "sizeSqft": 6200,
        "priceAED": 18500000,
        "rentAED": 850000,
        "style": "classic",
        "description": "Mature-garden villa on Jumeirah Beach Road with private pool and beach access nearby.",
        "amenities": ["pool", "garden", "maid room", "parking", "beach access"],
        "pricePerSqft": 2984,
        "lat": 25.2048,
        "lng": 55.2396,
        "cameraHeading": 270,
        "images": [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Aisha Bin Rashid",
            "agency": "Jumeirah Estates",
            "phone": "+971 50 333 4455",
            "whatsapp": "971503334455",
        },
    },
    {
        "id": "jm-modern-villa-4br",
        "title": "Jumeirah Modern Family Villa",
        "area": "Jumeirah",
        "type": "villa",
        "bedrooms": 4,
        "bathrooms": 5,
        "sizeSqft": 4800,
        "priceAED": 14200000,
        "rentAED": 620000,
        "style": "modern",
        "description": "New-build contemporary villa with smart home, landscaped garden, and close to top schools.",
        "amenities": ["pool", "garden", "smart home", "gym", "maid room", "parking"],
        "pricePerSqft": 2958,
        "lat": 25.2102,
        "lng": 55.2451,
        "cameraHeading": 180,
        "images": [
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "David Morrison",
            "agency": "Coastal Villas DXB",
            "phone": "+971 55 666 7788",
            "whatsapp": "971556667788",
        },
    },
    {
        "id": "jm-townhouse-3br",
        "title": "Jumeirah Park Townhouse",
        "area": "Jumeirah",
        "type": "townhouse",
        "bedrooms": 3,
        "bathrooms": 4,
        "sizeSqft": 2600,
        "priceAED": 5200000,
        "rentAED": 280000,
        "style": "modern",
        "description": "End-unit townhouse in a gated community with community pool and kids' play areas.",
        "amenities": ["pool", "play area", "garden", "parking", "gated community"],
        "pricePerSqft": 2000,
        "lat": 25.1985,
        "lng": 55.2512,
        "images": [
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Priya Sharma",
            "agency": "Park Living",
            "phone": "+971 52 888 9900",
            "whatsapp": "971528889900",
        },
    },
    {
        "id": "jm-luxury-penthouse",
        "title": "La Mer Penthouse",
        "area": "Jumeirah",
        "type": "penthouse",
        "bedrooms": 3,
        "bathrooms": 4,
        "sizeSqft": 3100,
        "priceAED": 9800000,
        "rentAED": 480000,
        "style": "luxury",
        "description": "Waterfront penthouse at La Mer with sea views, private elevator, and beach club access.",
        "amenities": ["sea view", "pool", "beach club", "concierge", "parking"],
        "pricePerSqft": 3161,
        "lat": 25.2285,
        "lng": 55.2558,
        "cameraHeading": 90,
        "images": [
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Noor Al Farsi",
            "agency": "La Mer Luxury",
            "phone": "+971 50 222 3344",
            "whatsapp": "971502223344",
        },
    },
    {
        "id": "jm-arabesque-villa",
        "title": "Arabesque Heritage Villa",
        "area": "Jumeirah",
        "type": "villa",
        "bedrooms": 6,
        "bathrooms": 7,
        "sizeSqft": 8500,
        "priceAED": 24000000,
        "rentAED": 1100000,
        "style": "arabesque",
        "description": "Grand villa with mashrabiya details, courtyard fountain, and staff quarters in old Jumeirah.",
        "amenities": ["pool", "courtyard", "maid room", "staff quarters", "garden", "parking"],
        "pricePerSqft": 2824,
        "lat": 25.2015,
        "lng": 55.2342,
        "images": [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Khalid Al Mansoori",
            "agency": "Heritage Homes",
            "phone": "+971 56 111 2233",
            "whatsapp": "971561112233",
        },
    },
    {
        "id": "jm-minimal-2br",
        "title": "Jumeirah Minimal Apartment",
        "area": "Jumeirah",
        "type": "apartment",
        "bedrooms": 2,
        "bathrooms": 2,
        "sizeSqft": 1350,
        "priceAED": 2650000,
        "rentAED": 155000,
        "style": "minimalist",
        "description": "Quiet boutique building with clean lines, natural light, and easy access to Jumeirah Beach.",
        "amenities": ["gym", "parking", "balcony", "beach access"],
        "pricePerSqft": 1963,
        "lat": 25.2078,
        "lng": 55.2410,
        "images": [
            "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Emma Walsh",
            "agency": "Coastline Living",
            "phone": "+971 52 555 6677",
            "whatsapp": "971525556677",
        },
    },
    {
        "id": "dt-rent-2br",
        "title": "Downtown Creek View Rental",
        "area": "Downtown Dubai",
        "type": "apartment",
        "bedrooms": 2,
        "bathrooms": 2,
        "sizeSqft": 1280,
        "priceAED": 2400000,
        "rentAED": 140000,
        "style": "modern",
        "description": "Well-priced rental-friendly two-bed with creek views and full building amenities.",
        "amenities": ["creek view", "gym", "pool", "parking"],
        "pricePerSqft": 1875,
        "lat": 25.1925,
        "lng": 55.2788,
        "images": [
            "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Raj Patel",
            "agency": "Rent Smart DXB",
            "phone": "+971 50 444 5566",
            "whatsapp": "971504445566",
        },
    },
    {
        "id": "jm-family-rent-4br",
        "title": "Jumeirah Family Rental Villa",
        "area": "Jumeirah",
        "type": "villa",
        "bedrooms": 4,
        "bathrooms": 5,
        "sizeSqft": 4200,
        "priceAED": 9800000,
        "rentAED": 420000,
        "style": "classic",
        "description": "Four-bedroom villa ideal for families — large garden, near schools, and annual lease available.",
        "amenities": ["garden", "pool", "maid room", "play area", "parking"],
        "pricePerSqft": 2333,
        "lat": 25.2062,
        "lng": 55.2478,
        "images": [
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Sana Ibrahim",
            "agency": "Family Rentals UAE",
            "phone": "+971 55 777 8899",
            "whatsapp": "971557778899",
        },
    },
    {
        "id": "dt-3br-budget",
        "title": "Business Bay Adjacent 3-Bed",
        "area": "Downtown Dubai",
        "type": "apartment",
        "bedrooms": 3,
        "bathrooms": 3,
        "sizeSqft": 1850,
        "priceAED": 3100000,
        "rentAED": 175000,
        "style": "modern",
        "description": "Value three-bedroom near Downtown with canal views — great for families on a tighter budget.",
        "amenities": ["canal view", "gym", "pool", "parking", "play area"],
        "pricePerSqft": 1676,
        "lat": 25.1905,
        "lng": 55.2695,
        "images": [
            "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Tom Bradley",
            "agency": "Value Homes DXB",
            "phone": "+971 52 333 2211",
            "whatsapp": "971523332211",
        },
    },
    {
        "id": "ad-reem-family-4br",
        "title": "Al Reem Island Family Residence",
        "city": "Abu Dhabi",
        "area": "Al Reem Island",
        "type": "apartment",
        "bedrooms": 4,
        "bathrooms": 4,
        "sizeSqft": 2450,
        "priceAED": 3200000,
        "rentAED": 185000,
        "style": "modern",
        "description": "Spacious family apartment on Al Reem Island — balanced commute to Hub71 and Khalifa City schools.",
        "amenities": ["sea view", "gym", "pool", "play area", "parking", "schools"],
        "pricePerSqft": 1306,
        "nearLandmarks": ["Hub71", "ISC Khalifa"],
        "lat": 24.4945,
        "lng": 54.4068,
        "images": [
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Layla Al Mansoori",
            "agency": "Reem Living",
            "phone": "+971 50 211 3344",
            "whatsapp": "971502113344",
        },
    },
    {
        "id": "ad-khalifa-villa-5br",
        "title": "Khalifa City Family Villa",
        "city": "Abu Dhabi",
        "area": "Khalifa City",
        "type": "villa",
        "bedrooms": 5,
        "bathrooms": 6,
        "sizeSqft": 5100,
        "priceAED": 4500000,
        "rentAED": 240000,
        "style": "classic",
        "description": "Large villa minutes from ISC Khalifa (SABIS) with garden, maid's room, and quiet family streets.",
        "amenities": ["garden", "pool", "maid room", "play area", "parking", "schools"],
        "pricePerSqft": 882,
        "nearLandmarks": ["ISC Khalifa"],
        "lat": 24.4258,
        "lng": 54.5745,
        "images": [
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Ahmed Al Ketbi",
            "agency": "Khalifa Homes",
            "phone": "+971 55 311 4455",
            "whatsapp": "971553114455",
        },
    },
    {
        "id": "ad-reem-commute-3br",
        "title": "Reem Commuter Apartment",
        "city": "Abu Dhabi",
        "area": "Al Reem Island",
        "type": "apartment",
        "bedrooms": 3,
        "bathrooms": 3,
        "sizeSqft": 1750,
        "priceAED": 2100000,
        "rentAED": 135000,
        "style": "minimalist",
        "description": "Bright three-bedroom close to the Reem Island promenade with quick access toward Hub71 and school routes.",
        "amenities": ["gym", "pool", "balcony", "parking", "schools"],
        "pricePerSqft": 1200,
        "nearLandmarks": ["Hub71", "ISC Khalifa"],
        "lat": 24.4988,
        "lng": 54.4012,
        "images": [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Nadia Rahman",
            "agency": "Capital Commute",
            "phone": "+971 52 422 5566",
            "whatsapp": "971524225566",
        },
    },
    {
        "id": "ad-maryah-hub71-2br",
        "title": "Maryah Island Hub71 Walkable Flat",
        "city": "Abu Dhabi",
        "area": "Al Maryah Island",
        "type": "apartment",
        "bedrooms": 2,
        "bathrooms": 2,
        "sizeSqft": 1280,
        "priceAED": 2400000,
        "rentAED": 155000,
        "style": "modern",
        "description": "Modern two-bedroom walking distance to Hub71 and ADGM — ideal if work is the top priority.",
        "amenities": ["gym", "concierge", "parking", "city view"],
        "pricePerSqft": 1875,
        "nearLandmarks": ["Hub71"],
        "lat": 24.5004,
        "lng": 54.3887,
        "images": [
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Karim Hassan",
            "agency": "Maryah Estates",
            "phone": "+971 50 533 6677",
            "whatsapp": "971505336677",
        },
    },
    {
        "id": "ad-khalifa-townhouse-4br",
        "title": "Khalifa City Townhouse",
        "city": "Abu Dhabi",
        "area": "Khalifa City",
        "type": "townhouse",
        "bedrooms": 4,
        "bathrooms": 5,
        "sizeSqft": 2900,
        "priceAED": 2850000,
        "rentAED": 165000,
        "style": "modern",
        "description": "End-unit townhouse near school buses and parks — strong pick for families with kids at ISC Khalifa.",
        "amenities": ["garden", "play area", "gym", "parking", "schools"],
        "pricePerSqft": 983,
        "nearLandmarks": ["ISC Khalifa"],
        "lat": 24.4312,
        "lng": 54.5688,
        "images": [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Priya Menon",
            "agency": "Schoolside Homes",
            "phone": "+971 56 644 7788",
            "whatsapp": "971566447788",
        },
    },
    {
        "id": "ad-reem-bridge-4br",
        "title": "Reem Bridge View Home",
        "city": "Abu Dhabi",
        "area": "Al Reem Island",
        "type": "apartment",
        "bedrooms": 4,
        "bathrooms": 4,
        "sizeSqft": 2600,
        "priceAED": 3500000,
        "rentAED": 195000,
        "style": "luxury",
        "description": "Premium four-bedroom on Reem with fast links to both Hub71 and Khalifa City — our top pick for dual commutes.",
        "amenities": ["sea view", "gym", "pool", "concierge", "play area", "schools", "parking"],
        "pricePerSqft": 1346,
        "nearLandmarks": ["Hub71", "ISC Khalifa"],
        "lat": 24.4921,
        "lng": 54.3955,
        "images": [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Omar Al Farsi",
            "agency": "Dual Commute Realty",
            "phone": "+971 55 755 8899",
            "whatsapp": "971557558899",
        },
    },
    {
        "id": "ad-saadiyat-family-4br",
        "title": "Saadiyat Family Villa",
        "city": "Abu Dhabi",
        "area": "Saadiyat Island",
        "type": "villa",
        "bedrooms": 4,
        "bathrooms": 5,
        "sizeSqft": 4300,
        "priceAED": 5200000,
        "rentAED": 280000,
        "style": "luxury",
        "description": "Quiet Saadiyat villa with beach access and excellent schools — longer commute to Hub71 but premium family lifestyle.",
        "amenities": ["beach access", "pool", "garden", "maid room", "schools", "parking"],
        "pricePerSqft": 1209,
        "nearLandmarks": [],
        "lat": 24.5398,
        "lng": 54.4345,
        "images": [
            "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80",
        ],
        "broker": {
            "name": "Emma Clarke",
            "agency": "Saadiyat Living",
            "phone": "+971 52 866 9900",
            "whatsapp": "971528669900",
        },
    },
]
