import type { Property } from "./types";

const downtownImages = [
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1200&q=80",
];

const villaImages = [
  "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
];

export const SEED_PROPERTIES: Property[] = [
  {
    id: "downtown-burj-view-01",
    title: "Burj Vista Family Residence",
    area: "Downtown Dubai",
    type: "apartment",
    bedrooms: 3,
    bathrooms: 4,
    sizeSqft: 1905,
    priceAED: 6900000,
    rentAED: 420000,
    style: "modern",
    description:
      "A bright Downtown apartment framed around the Burj Khalifa skyline, with family-ready living space and direct access to central Dubai amenities.",
    amenities: ["burj view", "pool", "gym", "parking", "balcony", "family-friendly"],
    pricePerSqft: 3622,
    lat: 25.197197,
    lng: 55.274376,
    cameraHeading: 210,
    images: [downtownImages[0], downtownImages[1]],
    broker: {
      name: "Maya Haddad",
      agency: "Palmline Estates",
      phone: "+971 50 123 4567",
      whatsapp: "971501234567",
    },
    source: "seed",
  },
  {
    id: "jumeirah-garden-villa-01",
    title: "Jumeirah Garden Villa",
    area: "Jumeirah",
    type: "villa",
    bedrooms: 4,
    bathrooms: 5,
    sizeSqft: 4200,
    priceAED: 12500000,
    rentAED: 750000,
    style: "luxury",
    description:
      "A private Jumeirah villa with generous family rooms, a landscaped garden, and quick access to the beach-side neighborhood core.",
    amenities: ["garden", "pool", "parking", "maid room", "beach access", "family-friendly"],
    pricePerSqft: 2976,
    lat: 25.21987,
    lng: 55.25461,
    cameraHeading: 125,
    images: [villaImages[0], villaImages[1]],
    broker: {
      name: "Omar Rahman",
      agency: "Coastal Key Properties",
      phone: "+971 55 987 6543",
      whatsapp: "971559876543",
    },
    source: "seed",
  },
  {
    id: "downtown-opera-minimal-02",
    title: "Opera District Minimalist Loft",
    area: "Downtown Dubai",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 3,
    sizeSqft: 1410,
    priceAED: 4300000,
    rentAED: 285000,
    style: "minimalist",
    description: "A clean-lined residence near Dubai Opera with a quiet palette, open living room, and a balcony angled toward the boulevard.",
    amenities: ["pool", "gym", "balcony", "parking", "metro access"],
    pricePerSqft: 3050,
    lat: 25.19452,
    lng: 55.27236,
    cameraHeading: 185,
    images: [downtownImages[1]],
    broker: { name: "Leen Farah", agency: "Axis Urban Homes", phone: "+971 52 222 1188", whatsapp: "971522221188" },
    source: "seed",
  },
  {
    id: "downtown-address-luxury-03",
    title: "Address Boulevard Sky Suite",
    area: "Downtown Dubai",
    type: "penthouse",
    bedrooms: 4,
    bathrooms: 5,
    sizeSqft: 3540,
    priceAED: 18900000,
    rentAED: 980000,
    style: "luxury",
    description: "A high-floor penthouse with hotel-serviced amenities, a broad skyline terrace, and full Downtown arrival energy.",
    amenities: ["burj view", "pool", "gym", "concierge", "terrace", "parking"],
    pricePerSqft: 5339,
    lat: 25.20049,
    lng: 55.27762,
    cameraHeading: 245,
    images: [downtownImages[2], downtownImages[0]],
    broker: { name: "Nadia Salem", agency: "Vista Prime", phone: "+971 56 444 0192", whatsapp: "971564440192" },
    source: "seed",
  },
  {
    id: "downtown-boulevard-classic-04",
    title: "Classic Boulevard Apartment",
    area: "Downtown Dubai",
    type: "apartment",
    bedrooms: 1,
    bathrooms: 2,
    sizeSqft: 910,
    priceAED: 2200000,
    rentAED: 165000,
    style: "classic",
    description: "A warm one-bedroom overlooking Mohammed Bin Rashid Boulevard with practical storage and an easy walk to Dubai Mall.",
    amenities: ["pool", "gym", "parking", "mall access"],
    pricePerSqft: 2418,
    lat: 25.19198,
    lng: 55.27843,
    cameraHeading: 260,
    images: [downtownImages[0]],
    broker: { name: "Rami Nasser", agency: "Metroline Realty", phone: "+971 50 808 3030", whatsapp: "971508083030" },
    source: "seed",
  },
  {
    id: "downtown-industrial-05",
    title: "Industrial Studio by Business Bay Edge",
    area: "Downtown Dubai",
    type: "apartment",
    bedrooms: 0,
    bathrooms: 1,
    sizeSqft: 610,
    priceAED: 1350000,
    rentAED: 115000,
    style: "industrial",
    description: "A compact studio with dark metal finishes and fast access to Downtown, Business Bay, and the canal.",
    amenities: ["gym", "parking", "canal access", "security"],
    pricePerSqft: 2213,
    lat: 25.18798,
    lng: 55.28022,
    cameraHeading: 190,
    images: [downtownImages[1]],
    broker: { name: "Ibrahim Zaki", agency: "Core Door Properties", phone: "+971 58 700 9921", whatsapp: "971587009921" },
    source: "seed",
  },
  {
    id: "downtown-arabesque-06",
    title: "Arabesque Residence near Old Town",
    area: "Downtown Dubai",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 3,
    sizeSqft: 1560,
    priceAED: 3850000,
    rentAED: 260000,
    style: "arabesque",
    description: "A two-bedroom residence with carved details, shaded balconies, and a calmer Old Town feel close to the fountains.",
    amenities: ["balcony", "pool", "parking", "fountain view", "family-friendly"],
    pricePerSqft: 2468,
    lat: 25.19136,
    lng: 55.27499,
    cameraHeading: 230,
    images: [downtownImages[2]],
    broker: { name: "Alya Mansour", agency: "Courtyard Estates", phone: "+971 55 410 2221", whatsapp: "971554102221" },
    source: "seed",
  },
  {
    id: "downtown-modern-07",
    title: "Modern Three-Bed on Sheikh Mohammed Boulevard",
    area: "Downtown Dubai",
    type: "apartment",
    bedrooms: 3,
    bathrooms: 4,
    sizeSqft: 2020,
    priceAED: 5850000,
    rentAED: 390000,
    style: "modern",
    description: "A practical family apartment with a broad living room, two balconies, and a short walk to the Dubai Mall link.",
    amenities: ["pool", "gym", "parking", "balcony", "family-friendly", "mall access"],
    pricePerSqft: 2896,
    lat: 25.19581,
    lng: 55.28011,
    cameraHeading: 205,
    images: [downtownImages[0], downtownImages[2]],
    broker: { name: "Samir Khatib", agency: "Northline Homes", phone: "+971 54 311 4470", whatsapp: "971543114470" },
    source: "seed",
  },
  {
    id: "downtown-penthouse-08",
    title: "Fountain-Facing Penthouse",
    area: "Downtown Dubai",
    type: "penthouse",
    bedrooms: 3,
    bathrooms: 4,
    sizeSqft: 2750,
    priceAED: 12400000,
    rentAED: 720000,
    style: "luxury",
    description: "A penthouse set above the fountain district with a terrace made for evening views and formal entertaining.",
    amenities: ["fountain view", "burj view", "terrace", "pool", "concierge", "parking"],
    pricePerSqft: 4509,
    lat: 25.1933,
    lng: 55.2772,
    cameraHeading: 215,
    images: [downtownImages[2], downtownImages[1]],
    broker: { name: "Dana Hariri", agency: "Crescent Private Office", phone: "+971 52 909 1717", whatsapp: "971529091717" },
    source: "seed",
  },
  {
    id: "downtown-family-09",
    title: "Family Residence near Burj Park",
    area: "Downtown Dubai",
    type: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    sizeSqft: 1810,
    priceAED: 5100000,
    rentAED: 350000,
    style: "minimalist",
    description: "A calm three-bedroom beside Burj Park with practical proportions, storage, and building amenities for daily family use.",
    amenities: ["park access", "pool", "gym", "parking", "family-friendly"],
    pricePerSqft: 2818,
    lat: 25.1907,
    lng: 55.2718,
    cameraHeading: 170,
    images: [downtownImages[1], downtownImages[0]],
    broker: { name: "Mariam Qureshi", agency: "Parkline Advisory", phone: "+971 50 707 4044", whatsapp: "971507074044" },
    source: "seed",
  },
  {
    id: "jumeirah-beach-modern-02",
    title: "Modern Beachside Townhouse",
    area: "Jumeirah",
    type: "townhouse",
    bedrooms: 3,
    bathrooms: 4,
    sizeSqft: 2850,
    priceAED: 6900000,
    rentAED: 430000,
    style: "modern",
    description: "A bright townhouse close to Jumeirah Beach with a roof terrace, easy parking, and indoor-outdoor family space.",
    amenities: ["beach access", "terrace", "parking", "family-friendly", "maid room"],
    pricePerSqft: 2421,
    lat: 25.21372,
    lng: 55.24789,
    cameraHeading: 110,
    images: [villaImages[1]],
    broker: { name: "Farah Al Nuaimi", agency: "Shoreline Homes", phone: "+971 56 330 8021", whatsapp: "971563308021" },
    source: "seed",
  },
  {
    id: "jumeirah-classic-03",
    title: "Classic Jumeirah Courtyard Villa",
    area: "Jumeirah",
    type: "villa",
    bedrooms: 5,
    bathrooms: 6,
    sizeSqft: 5600,
    priceAED: 16800000,
    rentAED: 950000,
    style: "classic",
    description: "A substantial villa built around a private courtyard with formal reception rooms and a generous family garden.",
    amenities: ["garden", "pool", "maid room", "driver room", "parking", "family-friendly"],
    pricePerSqft: 3000,
    lat: 25.23078,
    lng: 55.25725,
    cameraHeading: 130,
    images: [villaImages[2], villaImages[0]],
    broker: { name: "Karim Youssef", agency: "Majlis Realty", phone: "+971 50 668 1200", whatsapp: "971506681200" },
    source: "seed",
  },
  {
    id: "jumeirah-minimal-04",
    title: "Minimalist Villa near Kite Beach",
    area: "Jumeirah",
    type: "villa",
    bedrooms: 4,
    bathrooms: 5,
    sizeSqft: 3900,
    priceAED: 10900000,
    rentAED: 680000,
    style: "minimalist",
    description: "A crisp, low-profile villa with pale interiors, a shaded pool deck, and quick access to Kite Beach.",
    amenities: ["beach access", "pool", "garden", "parking", "maid room"],
    pricePerSqft: 2795,
    lat: 25.19901,
    lng: 55.23869,
    cameraHeading: 95,
    images: [villaImages[1], villaImages[2]],
    broker: { name: "Sarah Malik", agency: "Kite & Key", phone: "+971 55 201 8820", whatsapp: "971552018820" },
    source: "seed",
  },
  {
    id: "jumeirah-arabesque-05",
    title: "Arabesque Garden Home",
    area: "Jumeirah",
    type: "villa",
    bedrooms: 4,
    bathrooms: 5,
    sizeSqft: 4450,
    priceAED: 11800000,
    rentAED: 720000,
    style: "arabesque",
    description: "A private family home with patterned screens, warm stone finishes, and a sheltered garden made for evenings outside.",
    amenities: ["garden", "pool", "maid room", "parking", "family-friendly"],
    pricePerSqft: 2652,
    lat: 25.22048,
    lng: 55.24344,
    cameraHeading: 145,
    images: [villaImages[0], villaImages[2]],
    broker: { name: "Hessa Al Marri", agency: "Palm Gate Realty", phone: "+971 52 618 0909", whatsapp: "971526180909" },
    source: "seed",
  },
  {
    id: "jumeirah-industrial-06",
    title: "Converted Industrial Beach Loft",
    area: "Jumeirah",
    type: "townhouse",
    bedrooms: 2,
    bathrooms: 3,
    sizeSqft: 2250,
    priceAED: 5200000,
    rentAED: 330000,
    style: "industrial",
    description: "A rare townhouse-style loft with concrete textures, a private terrace, and a walkable Jumeirah setting.",
    amenities: ["terrace", "parking", "beach access", "security"],
    pricePerSqft: 2311,
    lat: 25.20847,
    lng: 55.25218,
    cameraHeading: 105,
    images: [villaImages[1]],
    broker: { name: "Zain Haddad", agency: "Raw House Dubai", phone: "+971 58 411 9000", whatsapp: "971584119000" },
    source: "seed",
  },
  {
    id: "jumeirah-luxury-07",
    title: "Signature Villa off Jumeirah Road",
    area: "Jumeirah",
    type: "villa",
    bedrooms: 6,
    bathrooms: 7,
    sizeSqft: 7300,
    priceAED: 24500000,
    rentAED: 1450000,
    style: "luxury",
    description: "A private signature villa with resort-style landscaping, staff quarters, and a long pool terrace.",
    amenities: ["garden", "pool", "driver room", "maid room", "parking", "smart home"],
    pricePerSqft: 3356,
    lat: 25.22614,
    lng: 55.25192,
    cameraHeading: 150,
    images: [villaImages[2], villaImages[0]],
    broker: { name: "Yara Ameen", agency: "Crown Coast Estates", phone: "+971 50 930 7100", whatsapp: "971509307100" },
    source: "seed",
  },
  {
    id: "jumeirah-apartment-08",
    title: "Low-Rise Jumeirah Apartment",
    area: "Jumeirah",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 1280,
    priceAED: 2750000,
    rentAED: 190000,
    style: "modern",
    description: "A low-rise apartment with a practical plan, soft modern finishes, and walkable access to cafes and the beach.",
    amenities: ["beach access", "parking", "balcony", "gym"],
    pricePerSqft: 2148,
    lat: 25.2183,
    lng: 55.26152,
    cameraHeading: 120,
    images: [downtownImages[1]],
    broker: { name: "Bilal Darwish", agency: "Coastline Collective", phone: "+971 54 616 2134", whatsapp: "971546162134" },
    source: "seed",
  },
  {
    id: "jumeirah-family-09",
    title: "Family Villa near Schools",
    area: "Jumeirah",
    type: "villa",
    bedrooms: 5,
    bathrooms: 5,
    sizeSqft: 5100,
    priceAED: 13200000,
    rentAED: 820000,
    style: "classic",
    description: "A family-focused villa with generous bedrooms, a shaded garden, and quick routes toward Jumeirah's schools.",
    amenities: ["garden", "pool", "maid room", "parking", "family-friendly", "school access"],
    pricePerSqft: 2588,
    lat: 25.21501,
    lng: 55.26408,
    cameraHeading: 135,
    images: [villaImages[0], villaImages[1]],
    broker: { name: "Layla Sayegh", agency: "School Run Realty", phone: "+971 55 877 6101", whatsapp: "971558776101" },
    source: "seed",
  },
  {
    id: "jumeirah-townhouse-10",
    title: "Quiet Townhouse behind Beach Road",
    area: "Jumeirah",
    type: "townhouse",
    bedrooms: 3,
    bathrooms: 3,
    sizeSqft: 2480,
    priceAED: 6100000,
    rentAED: 390000,
    style: "minimalist",
    description: "A tucked-away townhouse with refined interiors, a private patio, and a quieter street just behind Beach Road.",
    amenities: ["patio", "parking", "beach access", "family-friendly"],
    pricePerSqft: 2460,
    lat: 25.20472,
    lng: 55.24532,
    cameraHeading: 100,
    images: [villaImages[2]],
    broker: { name: "Tariq Hassan", agency: "Backstreet Homes", phone: "+971 52 903 4455", whatsapp: "971529034455" },
    source: "seed",
  },
];
